/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_nico_animbynative_PngLoader */

#ifndef _Included_com_nico_animbynative_PngLoader
#define _Included_com_nico_animbynative_PngLoader
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_nico_animbynative_PngLoader
 * Method:    loadPNGImage
 * Signature: (Ljava/lang/String;Landroid/view/Surface;)V
 */
JNIEXPORT void JNICALL Java_com_nico_animbynative_PngLoader_loadPNGImage
  (JNIEnv *, jobject, jstring, jobject);
//JNIEXPORT void JNICALL loadPNGImage(JNIEnv *, jobject, jstring, jobject);
#ifdef __cplusplus
}
#endif
#endif
